# Be sure to restart your server when you modify this file.

# Define an application-wide content security policy.
# See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

Rails.application.config.content_security_policy do |policy|
  asset_host = "https://assets.mesophotic.org"

  policy.default_src :self
  policy.font_src    :self, asset_host, "https://fonts.gstatic.com"
  policy.img_src     :self, :https, :data
  policy.object_src  :none
  policy.script_src  :self, asset_host, "https://challenges.cloudflare.com", "https://ga.jspm.io"
  policy.style_src   :self, :unsafe_inline, asset_host, "https://fonts.googleapis.com"
  policy.connect_src :self, "https://fonts.googleapis.com", "https://fonts.gstatic.com"
  policy.frame_src   "https://challenges.cloudflare.com"
end

# Generate nonces for script tags (importmap, javascript_include_tag).
Rails.application.config.content_security_policy_nonce_generator = ->(request) { SecureRandom.base64(16) }

# Only apply nonces to script-src. The Rails 8.1 default applies nonces to
# both script-src and style-src, but a nonce in style-src causes browsers to
# ignore 'unsafe-inline' (per CSP spec), breaking the 70+ views that use
# style="" attributes. unsafe-inline for styles is acceptable — even GitHub
# uses it — since CSS injection risk is far lower than script injection.
Rails.application.config.content_security_policy_nonce_directives = %w[script-src]

# Automatically add nonces to script tags generated by javascript_include_tag,
# javascript_importmap_tags, etc.
Rails.application.config.content_security_policy_nonce_auto = true

Rails.application.config.content_security_policy_report_only = false
