pin "rails_admin", preload: true
pin "rails_admin/src/rails_admin/base", to: "https://ga.jspm.io/npm:rails_admin@3.3.0/src/rails_admin/base.js"
pin "jquery", to: "https://ga.jspm.io/npm:jquery@3.7.1/dist/jquery.js"
pin "jquery-ui/", to: "https://ga.jspm.io/npm:jquery-ui@1.14.1/"
pin "@popperjs/core", to: "https://ga.jspm.io/npm:@popperjs/core@2.11.8/dist/esm/popper.js"
pin "bootstrap", to: "https://ga.jspm.io/npm:bootstrap@5.3.3/dist/js/bootstrap.esm.js"
pin "flatpickr", to: "https://ga.jspm.io/npm:flatpickr@4.6.13/dist/flatpickr.js"
pin "trix", to: "https://ga.jspm.io/npm:trix@2.1.12/dist/trix.esm.min.js"
pin "@rails/actiontext", to: "https://ga.jspm.io/npm:@rails/actiontext@8.0.200/app/assets/javascripts/actiontext.esm.js"
